apiVersion: v1
kind: Service
metadata:
  annotations:
    cnpg.io/pluginClientSecret: helloworld-client-tls
    cnpg.io/pluginPort: "9090"
    cnpg.io/pluginServerSecret: helloworld-server-tls
  labels:
    app: hello-world
    cnpg.io/pluginName: cnpg-i-hello-world.cloudnative-pg.io
  name: hello-world
  namespace: cnpg-system
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: cnpg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
    spec:
      containers:
      - args:
        - plugin
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:9090
        image: ghcr.io/microsoft/documentdb-kubernetes-operator/documentdb-sidecar-injector:preview
        name: cnpg-i-hello-world
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /server
          name: server
        - mountPath: /client
          name: client
      volumes:
      - name: server
        secret:
          secretName: helloworld-server-tls
      - name: client
        secret:
          secretName: helloworld-client-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld-client
  namespace: cnpg-system
spec:
  commonName: helloworld-client
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  renewBefore: 360h
  secretName: helloworld-client-tls
  usages:
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld-server
  namespace: cnpg-system
spec:
  commonName: hello-world
  dnsNames:
  - hello-world
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  renewBefore: 360h
  secretName: helloworld-server-tls
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cnpg-system
spec:
  selfSigned: {}
