apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: documentdb-operator-cluster-role
  labels:
    app.kubernetes.io/name: "documentdb-operator"
    app.kubernetes.io/managed-by: "Helm"
rules:
- apiGroups: ["db.microsoft.com"] # documentdb.microsoft.com permissions
  resources: ["documentdbs", "documentdbs/status", "documentdbs/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "pods", "endpoints", "leases", "serviceaccounts", "configmaps", "namespaces", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterrolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.fleet.azure.com"] # fleet permissions for multi-cluster services
  resources: ["serviceexports", "multiclusterservices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["clusters", "publications", "subscriptions", "clusters/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Backup permissions
- apiGroups: ["db.microsoft.com"]
  resources: ["backups", "backups/status", "backups/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ScheduledBackup permissions
- apiGroups: ["db.microsoft.com"]
  resources: ["scheduledbackups", "scheduledbackups/status", "scheduledbackups/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# CNPG Backup permissions
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["backups", "backups/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# VolumeSnapshotClass permissions
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotclasses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
