apiVersion: v1
kind: Namespace
metadata:
  name: documentdb-preview-ns
---

# DocumentDB Credentials Secret
#
# Connect using mongosh:
# mongosh 127.0.0.1:10260 -u your_documentdb_user -p YourDocumentDBPassword100 --authenticationMechanism SCRAM-SHA-256 --tls --tlsAllowInvalidCertificates
#
apiVersion: v1
kind: Secret
metadata:
  name: documentdb-credentials
  namespace: documentdb-preview-ns
type: Opaque
stringData:
  username: your_documentdb_user 
  password: YourDocumentDBPassword100        