# Namespace definition
apiVersion: v1
kind: Namespace
metadata:
  name: documentdb-preview-ns
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: Secret
metadata:
  name: documentdb-credentials
  namespace: documentdb-preview-ns
type: Opaque
stringData:
  username: docdb
  password: {{DOCUMENTDB_PASSWORD}}

---

apiVersion: documentdb.io/preview
kind: DocumentDB
metadata:
  name: documentdb-preview
  namespace: documentdb-preview-ns
spec:
  nodeCount: 1
  instancesPerNode: 1
  documentDBImage: {{DOCUMENTDB_IMAGE}}
  gatewayImage: {{GATEWAY_IMAGE}}
  resource:
    storage:
      pvcSize: 10Gi
  clusterReplication:
    highAvailability: true
    primary: {{PRIMARY_CLUSTER}}
    crossCloudNetworkingStrategy: Istio
    clusterList:
{{CLUSTER_LIST}}
  exposeViaService:
    serviceType: LoadBalancer
  logLevel: info

---

apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: documentdb-crp
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: documentdb-preview-ns
  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdate