//go:build !ignore_autogenerated

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by controller-gen. DO NOT EDIT.

package preview

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReplication) DeepCopyInto(out *ClusterReplication) {
	*out = *in
	if in.ClusterList != nil {
		in, out := &in.ClusterList, &out.ClusterList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReplication.
func (in *ClusterReplication) DeepCopy() *ClusterReplication {
	if in == nil {
		return nil
	}
	out := new(ClusterReplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDB) DeepCopyInto(out *DocumentDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status.TLS != nil {
		out.Status.TLS = in.Status.TLS.DeepCopy()
	}
	out.Status.Status = in.Status.Status
	out.Status.ConnectionString = in.Status.ConnectionString
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDB.
func (in *DocumentDB) DeepCopy() *DocumentDB {
	if in == nil {
		return nil
	}
	out := new(DocumentDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDBList) DeepCopyInto(out *DocumentDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DocumentDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDBList.
func (in *DocumentDBList) DeepCopy() *DocumentDBList {
	if in == nil {
		return nil
	}
	out := new(DocumentDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDBSpec) DeepCopyInto(out *DocumentDBSpec) {
	*out = *in
	out.Resource = in.Resource
	if in.ClusterReplication != nil {
		in, out := &in.ClusterReplication, &out.ClusterReplication
		*out = new(ClusterReplication)
		(*in).DeepCopyInto(*out)
	}
	out.ExposeViaService = in.ExposeViaService
	out.Timeouts = in.Timeouts
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(GatewayTLS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDBSpec.
func (in *DocumentDBSpec) DeepCopy() *DocumentDBSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDBStatus) DeepCopyInto(out *DocumentDBStatus) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDBStatus.
func (in *DocumentDBStatus) DeepCopy() *DocumentDBStatus {
	if in == nil {
		return nil
	}
	out := new(DocumentDBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeViaService) DeepCopyInto(out *ExposeViaService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeViaService.
func (in *ExposeViaService) DeepCopy() *ExposeViaService {
	if in == nil {
		return nil
	}
	out := new(ExposeViaService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
}

// DeepCopyInto for GatewayTLS
func (in *GatewayTLS) DeepCopyInto(out *GatewayTLS) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.Provided != nil {
		in, out := &in.Provided, &out.Provided
		*out = new(ProvidedTLS)
		**out = **in
	}
}

func (in *GatewayTLS) DeepCopy() *GatewayTLS {
	if in == nil {
		return nil
	}
	out := new(GatewayTLS)
	in.DeepCopyInto(out)
	return out
}

func (in *CertManagerTLS) DeepCopyInto(out *CertManagerTLS) {
	*out = *in
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}
func (in *CertManagerTLS) DeepCopy() *CertManagerTLS {
	if in == nil {
		return nil
	}
	out := new(CertManagerTLS)
	in.DeepCopyInto(out)
	return out
}

func (in *TLSStatus) DeepCopy() *TLSStatus {
	if in == nil {
		return nil
	}
	out := new(TLSStatus)
	*out = *in
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timeouts) DeepCopyInto(out *Timeouts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timeouts.
func (in *Timeouts) DeepCopy() *Timeouts {
	if in == nil {
		return nil
	}
	out := new(Timeouts)
	in.DeepCopyInto(out)
	return out
}
