FROM mcr.microsoft.com/mirror/docker/library/ubuntu:22.04 AS stage

ARG DocumentDB_VERSION=0.106-0
ENV DocumentDB_VERSION=${DocumentDB_VERSION}

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    jq curl sudo git make build-essential openssl pkg-config libssl-dev ca-certificates wget unzip \
    && rm -rf /var/lib/apt/lists/*

# Create documentdb user
RUN useradd -ms /bin/bash documentdb -G sudo
RUN echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/no-pass-ask

# Install rustup (which includes rustc and cargo) in user directory
ENV RUSTUP_HOME=/home/documentdb/.rustup \
    CARGO_HOME=/home/documentdb/.cargo \
    PATH=/home/documentdb/.cargo/bin:$PATH

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain stable

RUN rustc --version && cargo --version

USER documentdb
WORKDIR /home/documentdb/code/

# Get the docuemntdb repository
RUN sudo chown -R documentdb:documentdb /home/documentdb/
# For local builds, copy the code over directly
COPY --chown=documentdb:documentdb . /home/documentdb/code/documentdb-${DocumentDB_VERSION}


WORKDIR /home/documentdb/code/documentdb-${DocumentDB_VERSION}/pg_documentdb_gw

# Compile the code
RUN cargo build

#------------------------------------------------------------------------------------------------

FROM mcr.microsoft.com/mirror/docker/library/ubuntu:22.04 AS final
ARG DocumentDB_VERSION=0.106-0
ENV DocumentDB_VERSION=${DocumentDB_VERSION}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    jq openssl lsof sudo ca-certificates postgresql-client && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

ENV LANGUAGE=en_US.UTF-8 \
    TERM=xterm-256color \
    OTEL_TRACING_ENABLED=true \
    OTEL_METRICS_ENABLED=true \
    OTEL_LOGGING_ENABLED=true \
    OTEL_LOGS_CONSOLE_ENABLED=true \
    PGHOST=localhost

# Create documentdb user
RUN useradd -ms /bin/bash documentdb -G sudo
RUN echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/no-pass-ask

USER documentdb

RUN mkdir /home/documentdb/gateway
RUN mkdir -p /home/documentdb/gateway/pg_documentdb_gw/target/release-with-symbols/

COPY --from=stage --chown=documentdb:documentdb /home/documentdb/code/documentdb-${DocumentDB_VERSION}/pg_documentdb_gw/target/debug/documentdb_gateway /home/documentdb/gateway/pg_documentdb_gw/target/release-with-symbols/documentdb_gateway
COPY --from=stage --chown=documentdb:documentdb /home/documentdb/code/documentdb-${DocumentDB_VERSION}/pg_documentdb_gw/SetupConfiguration.json /home/documentdb/gateway/pg_documentdb_gw/SetupConfiguration.json
COPY --from=stage --chown=documentdb:documentdb /home/documentdb/code/documentdb-${DocumentDB_VERSION}/scripts/build_and_start_gateway.sh /home/documentdb/gateway/scripts/build_and_start_gateway.sh
COPY --from=stage --chown=documentdb:documentdb /home/documentdb/code/documentdb-${DocumentDB_VERSION}/scripts/emulator_entrypoint.sh /home/documentdb/gateway/scripts/emulator_entrypoint.sh
COPY --from=stage --chown=documentdb:documentdb /home/documentdb/code/documentdb-${DocumentDB_VERSION}/scripts/utils.sh /home/documentdb/gateway/scripts/utils.sh

WORKDIR /home/documentdb/gateway/scripts
ENTRYPOINT ["/bin/bash", "-c", "/home/documentdb/gateway/scripts/emulator_entrypoint.sh \"$@\"", "--"]
