apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: documentdb-base
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: documentdb-operator
    - group: ""
      version: v1
      kind: Namespace
      name: cnpg-system
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: documentdbs.db.microsoft.com
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: publications.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: poolers.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: clusterimagecatalogs.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: imagecatalogs.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: scheduledbackups.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: backups.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: subscriptions.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: databases.postgresql.cnpg.io
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: clusters.postgresql.cnpg.io
    # RBAC roles and bindings
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRole
      name: documentdb-operator-cluster-role
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRole
      name: documentdb-operator-cloudnative-pg
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRole
      name: documentdb-operator-cloudnative-pg-edit
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRole
      name: documentdb-operator-cloudnative-pg-view
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRoleBinding
      name: documentdb-operator-cluster-rolebinding
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRoleBinding
      name: documentdb-operator-cloudnative-pg
    - group: "admissionregistration.k8s.io"
      version: v1
      kind: MutatingWebhookConfiguration
      name: cnpg-mutating-webhook-configuration
    - group: "admissionregistration.k8s.io"
      version: v1
      kind: ValidatingWebhookConfiguration
      name: cnpg-validating-webhook-configuration
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRole
      name: wal-replica-manager
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRoleBinding
      name: wal-replica-manager-binding
  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdate