apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: cert-manager-crp
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: cert-manager
    - group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRole
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRoleBinding
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
    - group: "admissionregistration.k8s.io"
      version: v1
      kind: MutatingWebhookConfiguration
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
    - group: "admissionregistration.k8s.io"
      version: v1
      kind: ValidatingWebhookConfiguration
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdate

---

apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ResourcePlacement
metadata:
  name: cert-manager-kube-system-rp
  namespace: kube-system
spec:
  resourceSelectors:
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: Role
      labelSelector:
        matchLabels:
          app: cert-manager
          app.kubernetes.io/instance: cert-manager
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: RoleBinding
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
  policy:
    placementType: PickAll
