//go:build !ignore_autogenerated

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by controller-gen. DO NOT EDIT.

package preview

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerTLS) DeepCopyInto(out *CertManagerTLS) {
	*out = *in
	out.IssuerRef = in.IssuerRef
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerTLS.
func (in *CertManagerTLS) DeepCopy() *CertManagerTLS {
	if in == nil {
		return nil
	}
	out := new(CertManagerTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReplication) DeepCopyInto(out *ClusterReplication) {
	*out = *in
	if in.ClusterList != nil {
		in, out := &in.ClusterList, &out.ClusterList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReplication.
func (in *ClusterReplication) DeepCopy() *ClusterReplication {
	if in == nil {
		return nil
	}
	out := new(ClusterReplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDB) DeepCopyInto(out *DocumentDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDB.
func (in *DocumentDB) DeepCopy() *DocumentDB {
	if in == nil {
		return nil
	}
	out := new(DocumentDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDBList) DeepCopyInto(out *DocumentDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DocumentDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDBList.
func (in *DocumentDBList) DeepCopy() *DocumentDBList {
	if in == nil {
		return nil
	}
	out := new(DocumentDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDBSpec) DeepCopyInto(out *DocumentDBSpec) {
	*out = *in
	out.Resource = in.Resource
	if in.ClusterReplication != nil {
		in, out := &in.ClusterReplication, &out.ClusterReplication
		*out = new(ClusterReplication)
		(*in).DeepCopyInto(*out)
	}
	out.ExposeViaService = in.ExposeViaService
	out.Timeouts = in.Timeouts
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDBSpec.
func (in *DocumentDBSpec) DeepCopy() *DocumentDBSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDBStatus) DeepCopyInto(out *DocumentDBStatus) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDBStatus.
func (in *DocumentDBStatus) DeepCopy() *DocumentDBStatus {
	if in == nil {
		return nil
	}
	out := new(DocumentDBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeViaService) DeepCopyInto(out *ExposeViaService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeViaService.
func (in *ExposeViaService) DeepCopy() *ExposeViaService {
	if in == nil {
		return nil
	}
	out := new(ExposeViaService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayTLS) DeepCopyInto(out *GatewayTLS) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.Provided != nil {
		in, out := &in.Provided, &out.Provided
		*out = new(ProvidedTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayTLS.
func (in *GatewayTLS) DeepCopy() *GatewayTLS {
	if in == nil {
		return nil
	}
	out := new(GatewayTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalEndpointsTLS) DeepCopyInto(out *GlobalEndpointsTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalEndpointsTLS.
func (in *GlobalEndpointsTLS) DeepCopy() *GlobalEndpointsTLS {
	if in == nil {
		return nil
	}
	out := new(GlobalEndpointsTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuerRef) DeepCopyInto(out *IssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuerRef.
func (in *IssuerRef) DeepCopy() *IssuerRef {
	if in == nil {
		return nil
	}
	out := new(IssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresTLS) DeepCopyInto(out *PostgresTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresTLS.
func (in *PostgresTLS) DeepCopy() *PostgresTLS {
	if in == nil {
		return nil
	}
	out := new(PostgresTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvidedTLS) DeepCopyInto(out *ProvidedTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvidedTLS.
func (in *ProvidedTLS) DeepCopy() *ProvidedTLS {
	if in == nil {
		return nil
	}
	out := new(ProvidedTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfiguration) DeepCopyInto(out *TLSConfiguration) {
	*out = *in
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresTLS)
		**out = **in
	}
	if in.GlobalEndpoints != nil {
		in, out := &in.GlobalEndpoints, &out.GlobalEndpoints
		*out = new(GlobalEndpointsTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfiguration.
func (in *TLSConfiguration) DeepCopy() *TLSConfiguration {
	if in == nil {
		return nil
	}
	out := new(TLSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSStatus) DeepCopyInto(out *TLSStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSStatus.
func (in *TLSStatus) DeepCopy() *TLSStatus {
	if in == nil {
		return nil
	}
	out := new(TLSStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageConfiguration) DeepCopyInto(out *StorageConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfiguration.
func (in *StorageConfiguration) DeepCopy() *StorageConfiguration {
	if in == nil {
		return nil
	}
	out := new(StorageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timeouts) DeepCopyInto(out *Timeouts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timeouts.
func (in *Timeouts) DeepCopy() *Timeouts {
	if in == nil {
		return nil
	}
	out := new(Timeouts)
	in.DeepCopyInto(out)
	return out
}
