name: Copy documentdb-sidecar-injector to GHCR

on:
  workflow_dispatch:
    inputs:
      source_registry:
        description: 'ACR registry name'
        required: true
        default: 'pgcosmoscontroller'
      repo:
        description: 'Source repository name'
        required: true
        default: 'cnpg-plugin'
      target_repo:
        description: 'Target GHCR repository name'
        required: true
        default: 'documentdb-sidecar-injector'
      source_tag:
        description: 'Source image tag'
        required: true
        default: 'v17'
      target_tag:
        description: 'Target image tag'
        required: true
        default: 'preview'

jobs:
  copy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to ACR
        run: |
          az acr login --name ${{ github.event.inputs.source_registry }}

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from ACR
        run: |
          docker pull ${{ github.event.inputs.source_registry }}.azurecr.io/${{ github.event.inputs.repo }}:${{ github.event.inputs.source_tag }}

      - name: Tag image for GHCR
        run: |
          docker tag ${{ github.event.inputs.source_registry }}.azurecr.io/${{ github.event.inputs.repo }}:${{ github.event.inputs.source_tag }} ghcr.io/${{ github.repository }}/${{ github.event.inputs.target_repo }}:${{ github.event.inputs.target_tag }}

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ github.event.inputs.target_repo }}:${{ github.event.inputs.target_tag }}