name: Publish Helm Chart to GHCR

on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: 'Helm chart version'
        required: false
        default: '0.0.1'
  push:
    branches:
      - main

env:
  CHART_NAME: documentdb-chart
  CHART_VERSION: ${{ github.event.inputs.chart_version || '0.0.1' }}
  GHCR_REPO: ghcr.io/${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: |
          helm dependency update documentdb-chart
          helm package $CHART_NAME --version $CHART_VERSION

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push Helm chart to GHCR
        run: |
          helm push /home/runner/work/documentdb-kubernetes-operator/documentdb-kubernetes-operator/documentdb-operator-${CHART_VERSION}.tgz oci://${GHCR_REPO}

