name: Integration Test - DocumentDB Operator

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  # Cluster configuration
  CERT_MANAGER_NS: cert-manager
  OPERATOR_NS: documentdb-operator
  DB_NS: documentdb-preview-ns
  DB_NAME: documentdb-preview
  # Connection parameters
  DB_USERNAME: default_user
  DB_PASSWORD: Admin100
  DB_PORT: 10260

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl netcat-openbsd

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Create kind cluster
      uses: helm/kind-action@v1.8.0
      with:
        cluster_name: documentdb-test

    - name: Install dependencies
      run: |
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        sudo apt-get update && sudo apt-get install -y mongodb-mongosh

    - name: Setup cluster
      run: |
        kubectl wait --for=condition=Ready nodes --all --timeout=300s
        
        helm repo add jetstack https://charts.jetstack.io && helm repo update
        helm install cert-manager jetstack/cert-manager \
          --namespace $CERT_MANAGER_NS --create-namespace \
          --set installCRDs=true --wait --timeout=5m
        
        helm install documentdb-operator oci://ghcr.io/microsoft/documentdb-kubernetes-operator/documentdb-operator \
          --version 0.0.1 --namespace $OPERATOR_NS --create-namespace --wait --timeout=8m

    - name: Deploy DocumentDB cluster
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${DB_NS}
        ---
        apiVersion: db.microsoft.com/preview
        kind: DocumentDB
        metadata:
          name: ${DB_NAME}
          namespace: ${DB_NS}
        spec:
          nodeCount: 1
          instancesPerNode: 1
          documentDBImage: ghcr.io/microsoft/documentdb/documentdb-local:16
          resource:
            pvcSize: 5Gi
          publicLoadBalancer:
            enabled: false
        EOF
        
        echo "DocumentDB resource created, waiting for cluster to be ready..."
        
        sleep 30
        
        timeout 600 bash -c '
        while true; do
          echo "Checking for DocumentDB pods..."
          kubectl get pods -n '$DB_NS' || true
          
          pod_count=$(kubectl get pods -n '$DB_NS' -l cnpg.io/cluster='$DB_NAME' --no-headers 2>/dev/null | wc -l)
          if [[ "$pod_count" -eq "0" ]]; then
            echo "No DocumentDB pods found yet, waiting..."
            sleep 15
            continue
          fi
          
          ready=$(kubectl get pods -n '$DB_NS' -l cnpg.io/cluster='$DB_NAME' -o json | jq ".items[] | select(.status.phase == \"Running\" and ([.status.containerStatuses[] | .ready] | all))" | jq -s "length")
          if [[ "$ready" -eq "1" ]]; then
            echo "DocumentDB cluster is ready!"
            break
          fi
          echo "Waiting for pods to be ready... ($ready/1 pods ready)"
          sleep 15
        done'
        
        echo "Final pod status:"
        kubectl get pods -n $DB_NS -o wide

    - name: Test connection with mongosh
      run: |
        echo "Testing connection with mongosh..."
        
        # Start port-forward in background
        kubectl port-forward pod/${DB_NAME}-1 $DB_PORT:$DB_PORT -n $DB_NS &
        PF_PID=$!
        
        # Wait for port-forward to be ready
        sleep 10
        
        # Test connection and run basic operations
        timeout 60 bash -c '
        until nc -z 127.0.0.1 '$DB_PORT'; do
          echo "Waiting for port-forward to be ready..."
          sleep 2
        done
        '
        
        echo "Port-forward is ready, testing mongosh connection..."
        
        # Create test script
        cat > test_mongosh.js << 'EOF'
        // Test basic connection and operations
        print("Connected to DocumentDB!");
        
        // Switch to test database
        use testdb;
        
        // Create collection and insert test data
        db.createCollection("test_collection");
        
        var result = db.test_collection.insertMany([
          { name: "Alice", age: 30, department: "Engineering" },
          { name: "Bob", age: 25, department: "Marketing" },
          { name: "Charlie", age: 35, department: "Sales" }
        ]);
        
        print("Inserted documents:", result.insertedIds);
        
        // Query the data
        var docs = db.test_collection.find().toArray();
        print("Found documents:", docs.length);
        
        // Test aggregation
        var avgAge = db.test_collection.aggregate([
          { $group: { _id: null, avgAge: { $avg: "$age" } } }
        ]).toArray();
        
        print("Average age:", avgAge[0].avgAge);
        
        // Test update
        db.test_collection.updateOne(
          { name: "Alice" },
          { $set: { title: "Senior Engineer" } }
        );
        
        // Verify update
        var alice = db.test_collection.findOne({ name: "Alice" });
        print("Alice after update:", alice);
        
        print("All tests passed!");
        EOF
        
        # Run the test
        mongosh 127.0.0.1:$DB_PORT \
          -u $DB_USERNAME \
          -p $DB_PASSWORD \
          --authenticationMechanism SCRAM-SHA-256 \
          --tls \
          --tlsAllowInvalidCertificates \
          --file test_mongosh.js
        
        # Clean up port-forward
        kill $PF_PID || true

    - name: Test with Python PyMongo client
      run: |
        echo "Testing with Python PyMongo client..."
        
        # Install Python dependencies
        pip install pymongo
        
        # Start port-forward in background
        kubectl port-forward pod/${DB_NAME}-1 $DB_PORT:$DB_PORT -n $DB_NS &
        PF_PID=$!
        
        # Wait for port-forward to be ready
        sleep 10
        
        # Run the existing Python test script
        cd scripts/test-scripts
        python3 mongo-python-data-pusher.py
        
        # Run additional Python tests
        cat > additional_test.py << 'EOF'
        from pymongo import MongoClient
        import ssl

        # Connection parameters
        client = MongoClient(
            "127.0.0.1",
            10260,
            username="default_user",
            password="Admin100",
            authSource="admin",
            authMechanism="SCRAM-SHA-256",
            tls=True,
            tlsAllowInvalidCertificates=True
        )

        # Test database operations
        test_db = client["integration_test"]
        
        # Test collection operations
        collection = test_db["test_collection"]
        
        # Insert test data
        docs = [
            {"type": "integration_test", "value": i, "status": "active"}
            for i in range(10)
        ]
        result = collection.insert_many(docs)
        print(f"Inserted {len(result.inserted_ids)} documents")
        
        # Test queries
        count = collection.count_documents({"status": "active"})
        print(f"Found {count} active documents")
        
        # Test aggregation
        pipeline = [
            {"$match": {"status": "active"}},
            {"$group": {"_id": "$status", "total": {"$sum": "$value"}}}
        ]
        agg_result = list(collection.aggregate(pipeline))
        print(f"Aggregation result: {agg_result}")
        
        # Test index creation
        collection.create_index("value")
        indexes = list(collection.list_indexes())
        print(f"Created indexes: {[idx['name'] for idx in indexes]}")
        
        print("Python integration tests passed!")
        
        client.close()
        EOF
        
        python3 additional_test.py
        
        # Clean up port-forward
        kill $PF_PID || true

    - name: Collect logs on failure
      if: failure()
      run: |
        echo "=== Collecting diagnostic information ==="
        
        # Check if kubectl is working
        if ! kubectl version --client &>/dev/null; then
          echo "kubectl not available"
          exit 0
        fi
        
        # Check if cluster is accessible
        if ! kubectl cluster-info &>/dev/null; then
          echo "Cluster not accessible"
          kubectl config current-context || echo "No kubectl context found"
          kubectl config get-contexts || echo "No contexts available"
          exit 0
        fi
        
        echo "=== Cluster nodes ==="
        kubectl get nodes -o wide || echo "Failed to get nodes"
        
        echo "=== All pods ==="
        kubectl get pods --all-namespaces -o wide || echo "Failed to get pods"
        
        echo "=== DocumentDB resources ==="
        kubectl get documentdb -n $DB_NS -o yaml || echo "Failed to get DocumentDB resources"
        
        echo "=== DocumentDB pod logs ==="
        kubectl logs -n $DB_NS -l cnpg.io/cluster=$DB_NAME --all-containers=true --tail=100 || echo "Failed to get DocumentDB pod logs"
        
        echo "=== DocumentDB pod description ==="
        kubectl describe pods -n $DB_NS -l cnpg.io/cluster=$DB_NAME || echo "Failed to describe DocumentDB pods"
        
        echo "=== Operator logs ==="
        kubectl logs -n $OPERATOR_NS deployment/documentdb-operator --tail=100 || echo "Failed to get operator logs"
        
        echo "=== cert-manager logs ==="
        kubectl logs -n $CERT_MANAGER_NS --all-containers=true --tail=50 || echo "Failed to get cert-manager logs"
        
        echo "=== Events ==="
        kubectl get events --all-namespaces --sort-by='.lastTimestamp' || echo "Failed to get events"
